name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main # Or your deployment branch, e.g., 'master'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # Standard runner environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Essential first step to get your code

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify the Node.js version your project uses.

      - name: Install dependencies and Build Project
        run: npm ci && npm run build
        # Optional: Add working-directory if your package.json is not at the repo root
        # working-directory: ./path/to/your/app

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}' # Provided automatically by GitHub Actions
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SIDH_JR }}'
          projectId: '312890115430' # <<< IMPORTANT: REPLACE THIS with your actual Firebase Project ID
          # channelId: live # Uncomment to deploy to 'live' channel (usually default)
          # only: hosting # Uncomment if you only want to deploy hosting
        env:
              ANOTHER_DEPLOY_CONFIG: 'production'
              # Accessing a secret to pass as an environment variable to a command
              MY_CUSTOM_API_KEY: ${{ secrets.MY_SPECIAL_API_KEY }}
